# Generated on Mon Aug  5 18:20:08 2019
__collection-name__: user-parameters

# This collection is used to set the user-parameters for Cheetah-3 robot.

kp : 1              # Proportional Gain
kd : 0.1            # Derivative Gain
tau_ff : 0.0        # Feed-forward Gain
zero : 0
calibrate : 0