__collection-name__: user-parameter-file

# Jpos_Controller
file_name : "jpos-user-parameters.yaml"

# Cheetah_Controller
file_name : "iust-user-parameters.yaml"
#file_name : "mc-mit-ctrl-user-parameters.yaml"