# Created by aligolestaneh on Aug 29 2022


__collection-name__: robot-parameters

controller_dt : 0.002
controler_mode: 0
myValue       : 1010

stand_kd_cartesian : [2.5, 2.5, 2.5]
stand_kp_cartesian : [50, 50, 50]

recovery_kp : [80, 80, 80]
recovery_kd : [1, 1, 1]

testValue    : 111
cheater_mode : 1 #(or 0)

foot_height_sensor_noise    : 0.001
foot_process_noise_position : 0.002
foot_sensor_noise_position  : 0.001
foot_sensor_noise_velocity  : 0.1
imu_process_noise_position  : 0.02
imu_process_noise_velocity  : 0.02

kpCOM   : [50, 50, 50]
kdCOM   : [10, 10, 10]
kpBase  : [300, 200, 100]
kdBase  : [20, 10, 10]

use_rc : 0 #(or 1)