# Generated on 01/22/2023 by aligolestaneh
__collection-name__: user-parameters
# Parameters for JOINT PD CONTROL

max_tau : 45.
max_iter : 50000
#　motor move param
move_range : 0.15
move_offset : 0.0
# motor selection
leg_enable : [1,0,0,0]
joint_enable : [0,1,0]
# control params
kp : [350,350,450]
kd : [8,13,15]
tau_ff : 0.0

zero : 0
calibrate : 0